### ISSUE TITLE
The head is shown broken

### ISSUE THREAD

**Issue by EscanorTargaryen** [OGminso/ChatHeadFont#4]
I just ran ‘mvn clean install’ and then put the plugin in the plugins folder.

![photo_2024-05-26_01-14-21](https://github.com/OGminso/ChatHeadFont/assets/57372280/c0e50041-1661-4876-92af-bee77c71110b)

Server: Spigot 1.20.4

**Comment by OGminso** [comment]
Issue seems to occur while loading the resource pack. Looking for a solution atm.

**Comment by OGminso** [comment]
If issues persists update the delay, if doesn't help ill look for another solution.
