### ISSUE TITLE
Adding the API

### ISSUE THREAD

**Issue by Siviis** [OGminso/ChatHeadFont#8]
I'm struggling to add the API to my project, i've added the jar to the build path and put this as the dependency in the pom file:

```
<dependency>
  	<groupId>net.minso</groupId>
  	<artifactId>ChatHead</artifactId>
  	<version>0.0.4-SNAPSHOT</version>
  </dependency>
```

  	
  I'm probably missing something silly, i havent added APIs to my projects in ages but even after looking it up i still can't get it to work

**Comment by garbyy** [comment]
https://jitpack.io/#OGminso/ChatHeadFont/API-v0.0.4
